# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gandoulf/epitech/PSU_project/rendu/malloc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gandoulf/epitech/PSU_project/rendu/malloc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gandoulf/epitech/PSU_project/rendu/malloc/CMakeFiles /home/gandoulf/epitech/PSU_project/rendu/malloc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gandoulf/epitech/PSU_project/rendu/malloc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named malloc

# Build rule for target.
malloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 malloc
.PHONY : malloc

# fast build rule for target.
malloc/fast:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/build
.PHONY : malloc/fast

findplace.o: findplace.c.o
.PHONY : findplace.o

# target to build an object file
findplace.c.o:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/findplace.c.o
.PHONY : findplace.c.o

findplace.i: findplace.c.i
.PHONY : findplace.i

# target to preprocess a source file
findplace.c.i:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/findplace.c.i
.PHONY : findplace.c.i

findplace.s: findplace.c.s
.PHONY : findplace.s

# target to generate assembly for a file
findplace.c.s:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/findplace.c.s
.PHONY : findplace.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/main.c.s
.PHONY : main.c.s

my_malloc.o: my_malloc.c.o
.PHONY : my_malloc.o

# target to build an object file
my_malloc.c.o:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/my_malloc.c.o
.PHONY : my_malloc.c.o

my_malloc.i: my_malloc.c.i
.PHONY : my_malloc.i

# target to preprocess a source file
my_malloc.c.i:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/my_malloc.c.i
.PHONY : my_malloc.c.i

my_malloc.s: my_malloc.c.s
.PHONY : my_malloc.s

# target to generate assembly for a file
my_malloc.c.s:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/my_malloc.c.s
.PHONY : my_malloc.c.s

resignedMemory.o: resignedMemory.c.o
.PHONY : resignedMemory.o

# target to build an object file
resignedMemory.c.o:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/resignedMemory.c.o
.PHONY : resignedMemory.c.o

resignedMemory.i: resignedMemory.c.i
.PHONY : resignedMemory.i

# target to preprocess a source file
resignedMemory.c.i:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/resignedMemory.c.i
.PHONY : resignedMemory.c.i

resignedMemory.s: resignedMemory.c.s
.PHONY : resignedMemory.s

# target to generate assembly for a file
resignedMemory.c.s:
	$(MAKE) -f CMakeFiles/malloc.dir/build.make CMakeFiles/malloc.dir/resignedMemory.c.s
.PHONY : resignedMemory.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... malloc"
	@echo "... rebuild_cache"
	@echo "... findplace.o"
	@echo "... findplace.i"
	@echo "... findplace.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... my_malloc.o"
	@echo "... my_malloc.i"
	@echo "... my_malloc.s"
	@echo "... resignedMemory.o"
	@echo "... resignedMemory.i"
	@echo "... resignedMemory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

